server:
  port: 9999
magic-api:
  #??web????
  web: /magic/web
  resource:
    #???????????classpath?????????
    #mac???????????
    #???????????????????????????Redis???????
    location: D:/data/magic-api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magic-api-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456